name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Тег релиза'
        required: false
        type: string

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Простейшая проверка
        run: echo "раннер получен, всё работает"
